# Generated by Django 5.0.1 on 2024-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ProductImage',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='product.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='product.size'),
        ),
    ]
